config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :products
  resources :users_admin, controller: 'users'
  devise_for :users
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_category
	has_many :products, through: :product_category

	validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :product_category
	has_many :categories, through: :product_category

	validates :description, :price, presence: true
	validates :price, numericality: true

	mount_uploader :image, ImageUploader
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
	belongs_to :product 
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX}
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @result = @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @result = @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
      format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @categories = Category.all

    respond_to do |format|
      if @result = @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @categories = Category.all
    
    respond_to do |format|
       if @result = @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.js {}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.fetch(:product, {}).permit(:image, :description, :price, category_ids: [], category_ids_attributes: [ :id ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  before_action :authenticate_user!

	  # GET /products/new
  def new
    @user = User.new
  end

  # POST /products
  # POST /products.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @result = @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for(category, data: { remote: true }) do |f| %>
    <fieldset class="form-group">
      <div class="form-group row">
        <%= f.label :name, :class => "col-xs-2 col-form-label" %>
        <div class="col-xs-10">
          <%= f.text_field :name, :class => "form-control" %>
        </div>
      </div>

    <div id="error_explanation">
      <% if category.errors.any? %>
        <% product.errors.full_messages.each do |message| %>
          <div class="alert alert-danger"><%= message %></div>
        <% end %>
      <% end %>
    </div>

      <div class="actions">
        <%= f.submit :class => "btn btn-success" %>
      </div>
    <fieldset class="form-group">
<% end %>

app/views/categories/create.js.erb
<% if @result %>
	$('#error_explanation').show();
	alert('Category was succesfully created');
<% else %>
	$('#error_explanation').html("<%= j(render 'shared/error_messages', object: @category) %>");
	$('#error_explanation').show();
<% end %>

app/views/categories/destroy.js.erb
$("#category_<%= @category.id %>").remove()

app/views/categories/edit.html.erb
<h2>Editing Category</h2>

<p>
	<%= link_to 'Back', categories_path, :class => "btn btn-secondary" %>
</p>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Categories</h1>
<p>
  <%= link_to 'Back', products_path, :class => "btn btn-secondary" %>
  <%= link_to 'New Category', new_category_path, :class => "btn btn-secondary" %>
</p>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr id="category_<%= category.id%>">
        <td><%= category.name %></td>
        <td><%= link_to 'Edit', edit_category_path(category), :class => "btn btn-secondary" %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?', remote: true }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h2>New Category</h1>

<p>
	<%= link_to 'Back', categories_path, :class => "btn btn-secondary" %>
</p>

<%= render 'form', category: @category %>

app/views/categories/update.js.erb
<% if @result %>
	$('#error_explanation').show();
	alert('Category was succesfully updated');
<% else %>
	$('#error_explanation').html("<%= j(render 'shared/error_messages', object: @category) %>");
	$('#error_explanation').show();
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warehouse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product, data: { remote: true }) do |f| %>
  <div class="field">
    <p>
      <div id="imagePreview"></div>
      <% if !@product['image'].blank? %>
       <%= image_tag @product.image_url, :id => "productImage" %>
      <% end %>
    </p>
    <fieldset class="form-group">
    <%= f.file_field :image, accept: 'image/png, image/gif, image/jpeg, image/jpg', id: 'uploadImage'%>
    <div class="form-group row">
      <%= f.label :description, :class => "col-xs-2 col-form-label" %>
      <div class="col-xs-10">
        <%= f.text_field :description, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :price, :class => "col-xs-2 col-form-label" %>
      <div class="col-xs-10">
        <%= f.text_field :price, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :categorie, :class => "col-xs-2 col-form-label" %>
      <div class="col-xs-10">
        <%= f.collection_select( :category_ids, @categories, :id, :name, {}, {:multiple => true}) %>
      </div>
    </div>
    
  </div>
  </fieldset>
  <div id="error_explanation">
    <% if product.errors.any? %>
      <% product.errors.full_messages.each do |message| %>
        <div class="alert alert-danger"><%= message %></div>
      <% end %>
    <% end %>
  </div>
    
  <div class="field">
    <%= f.submit :class => "btn btn-success" %>
  </div>

<% end %>

app/views/products/create.js.erb
<% if @result %>
	$("#error_explanation").hide();
	alert('Product was succesfully created');
<% else %>
	$('#error_explanation').html("<%= j(render 'shared/error_messages', object: @product) %>");
	$('#error_explanation').show();
<% end %>

app/views/products/destroy.js.erb
$("#product_<%= @product.id %>").remove()

app/views/products/edit.html.erb
<p>
	<%= link_to 'Back', products_path, :class => "btn btn-secondary"  %>
</p>
<h2>Editing Product</h2>

<%= render 'form', product: @product, categories: @categories %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Categories', categories_path, :class => "btn btn-secondary" %>
<%= link_to 'Add users', new_users_admin_path, :class => "btn btn-secondary" %>
<%= link_to 'New Product', new_product_path, :class => "btn btn-secondary" %>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr id="product_<%= product.id%>">
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product, :class => "btn btn-secondary" %></td>
        <td><%= link_to 'Edit', edit_product_path(product), :class => "btn btn-secondary" %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?', remote: true }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h2>New Product</h2>
<p>
	<%= link_to 'Back', products_path, :class => "btn btn-secondary" %>
</p>
<%= render 'form', product: @product, categorie: @categorie %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<%= link_to 'Back', products_path, :class => "btn btn-secondary"  %>
	<%= link_to 'Edit', edit_product_path(@product), :class => "btn btn-secondary"  %>
</p>
<p>
	<% if !@product['image'].blank? %>
		<%= image_tag @product.image_url %>
	<% end %>
	<h6>
		<%= @product.description %>
	</h6>
	Price: <%= @product.price %>
</p>

app/views/products/update.js.erb
<% if @result %>
  	$("#error_explanation").hide();
 	 alert('Product was succesfully updated');
<% else %>
  	$('#error_explanation').html("<%= j(render 'shared/error_messages', object: @product) %>");
  	$('#error_explanation').show();
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <% object.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
    <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user, url: users_admin_index_path(user), data: { remote: true }) do |f| %>
  
<fieldset class="form-group">
</fieldset>

  <div class="form-group row">
    <%= f.label :email, :class => "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :password, :class => "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <%= f.password_field :password, :class => "form-control" %>
    </div>
  </div>

  <div id="error_explanation">
    <% if user.errors.any? %>
      <% product.errors.full_messages.each do |message| %>
        <div class="alert alert-danger"><%= message %></div>
      <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/users/create.js.erb
<% if @result %>
	$('#error_explanation').hide();
	alert('User was successfully created.')
<% else %>
	$('#error_explanation').html("<%= j(render 'shared/error_messages', object: @user) %>");
	$('#error_explanation').show();
<% end %>

app/views/users/new.html.erb
<h2>Add new user</h2>

<p>
	<%= link_to 'Back', products_path, :class => "btn btn-secondary" %>
</p>

<%= render 'form', user: @user %>